#!/bin/bash

echo "train"
python show_avg.py ./training15/logs/training_seed_1337.csv 39
python show_avg.py ./training15/logs/training_seed_2018.csv 39
python show_avg.py ./training15/logs/training_seed_3827.csv 39
python show_avg.py ./training15/logs/training_seed_4242.csv 39
python show_avg.py ./training15/logs/training_seed_4545.csv 39
python show_avg.py ./training15/logs/training_seed_5329.csv 39
python show_avg.py ./training15/logs/training_seed_6407.csv 39
python show_avg.py ./training15/logs/training_seed_6774.csv 39
python show_avg.py ./training15/logs/training_seed_7639.csv 39
python show_avg.py ./training15/logs/training_seed_9863.csv 39

echo "test"
python show_avg.py ./training15/logs/testing_seed_1337.csv 222
python show_avg.py ./training15/logs/testing_seed_2018.csv 222
python show_avg.py ./training15/logs/testing_seed_3827.csv 222
python show_avg.py ./training15/logs/testing_seed_4242.csv 222
python show_avg.py ./training15/logs/testing_seed_4545.csv 222
python show_avg.py ./training15/logs/testing_seed_5329.csv 222
python show_avg.py ./training15/logs/testing_seed_6407.csv 222
python show_avg.py ./training15/logs/testing_seed_6774.csv 222
python show_avg.py ./training15/logs/testing_seed_7639.csv 222
python show_avg.py ./training15/logs/testing_seed_9863.csv 222

