#!/bin/bash

echo "train"
python show_avg.py ./training50/logs/training_seed_1337.csv 131
python show_avg.py ./training50/logs/training_seed_2018.csv 131
python show_avg.py ./training50/logs/training_seed_3827.csv 131
python show_avg.py ./training50/logs/training_seed_4242.csv 131
python show_avg.py ./training50/logs/training_seed_4545.csv 131
python show_avg.py ./training50/logs/training_seed_5329.csv 131
python show_avg.py ./training50/logs/training_seed_6407.csv 131
python show_avg.py ./training50/logs/training_seed_6774.csv 131
python show_avg.py ./training50/logs/training_seed_7639.csv 131
python show_avg.py ./training50/logs/training_seed_9863.csv 131

echo "test"
python show_avg.py ./training50/logs/testing_seed_1337.csv 130
python show_avg.py ./training50/logs/testing_seed_2018.csv 130
python show_avg.py ./training50/logs/testing_seed_3827.csv 130
python show_avg.py ./training50/logs/testing_seed_4242.csv 130
python show_avg.py ./training50/logs/testing_seed_4545.csv 130
python show_avg.py ./training50/logs/testing_seed_5329.csv 130
python show_avg.py ./training50/logs/testing_seed_6407.csv 130
python show_avg.py ./training50/logs/testing_seed_6774.csv 130
python show_avg.py ./training50/logs/testing_seed_7639.csv 130
python show_avg.py ./training50/logs/testing_seed_9863.csv 130

