#!/bin/bash

echo "train"
python show_avg.py ./training20/logs/training_seed_1337.csv 52
python show_avg.py ./training20/logs/training_seed_2018.csv 52
python show_avg.py ./training20/logs/training_seed_3827.csv 52
python show_avg.py ./training20/logs/training_seed_4242.csv 52
python show_avg.py ./training20/logs/training_seed_4545.csv 52
python show_avg.py ./training20/logs/training_seed_5329.csv 52
python show_avg.py ./training20/logs/training_seed_6407.csv 52
python show_avg.py ./training20/logs/training_seed_6774.csv 52
python show_avg.py ./training20/logs/training_seed_7639.csv 52
python show_avg.py ./training20/logs/training_seed_9863.csv 52

echo "test"
python show_avg.py ./training20/logs/testing_seed_1337.csv 209
python show_avg.py ./training20/logs/testing_seed_2018.csv 209
python show_avg.py ./training20/logs/testing_seed_3827.csv 209
python show_avg.py ./training20/logs/testing_seed_4242.csv 209
python show_avg.py ./training20/logs/testing_seed_4545.csv 209
python show_avg.py ./training20/logs/testing_seed_5329.csv 209
python show_avg.py ./training20/logs/testing_seed_6407.csv 209
python show_avg.py ./training20/logs/testing_seed_6774.csv 209
python show_avg.py ./training20/logs/testing_seed_7639.csv 209
python show_avg.py ./training20/logs/testing_seed_9863.csv 209

