#!/bin/bash

echo "train"
python show_avg.py ./training40/logs/training_seed_1337.csv 105
python show_avg.py ./training40/logs/training_seed_2018.csv 105
python show_avg.py ./training40/logs/training_seed_3827.csv 105
python show_avg.py ./training40/logs/training_seed_4242.csv 105
python show_avg.py ./training40/logs/training_seed_4545.csv 105
python show_avg.py ./training40/logs/training_seed_5329.csv 105
python show_avg.py ./training40/logs/training_seed_6407.csv 105
python show_avg.py ./training40/logs/training_seed_6774.csv 105
python show_avg.py ./training40/logs/training_seed_7639.csv 105
python show_avg.py ./training40/logs/training_seed_6543.csv 105

echo "test"
python show_avg.py ./training40/logs/testing_seed_1337.csv 156
python show_avg.py ./training40/logs/testing_seed_2018.csv 156
python show_avg.py ./training40/logs/testing_seed_3827.csv 156
python show_avg.py ./training40/logs/testing_seed_4242.csv 156
python show_avg.py ./training40/logs/testing_seed_4545.csv 156
python show_avg.py ./training40/logs/testing_seed_5329.csv 156
python show_avg.py ./training40/logs/testing_seed_6407.csv 156
python show_avg.py ./training40/logs/testing_seed_6774.csv 156
python show_avg.py ./training40/logs/testing_seed_7639.csv 156
python show_avg.py ./training40/logs/testing_seed_6543.csv 156

